export const HIDE_MODALS = 'HIDE_MODALS';

export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const SHOW_LOGOUT_MODAL = 'SHOW_LOGOUT_MODAL';
export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL';

export const AUTHENTICATE = 'AUTHENTICATE';
